on:
  reddit:
    url: https://www.reddit.com/r/migraine/top/
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Escape Quotes
        id: escape
        run: |
          title="${{on.reddit.outputs.title}}"
          escaped_title=$(echo "$title" | sed "s/'/\\\'/g" | sed 's/"/\\"/g')
          echo "::set-output name=escaped_title::$escaped_title"
      - name: Modify URL
        id: url-modify
        run: |
          original_url="${{on.reddit.outputs.link}}"
          modified_url=$(echo "$original_url" | sed 's/www.reddit.com/www.rxddit.com/g')
          echo "::set-output name=modified_url::$modified_url"
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_REDDIT_TOP }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_REDDIT }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_REDDIT }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`Migraine - Reddit - Top 🏆`'\n'**${{steps.escape.outputs.escaped_title}}**'\n'${{steps.url-modify.outputs.modified_url}}"
